### ISSUE TITLE
crash on startup

### ISSUE THREAD

**Issue by barisusakli** [rbeer/nodebb-plugin-smoothshorts#19]
```
TypeError: Cannot read property 'useDomain' of null
    at upgrade (/home/saas/nodebb/node_modules/nodebb-plugin-smoothshorts/lib/settings.js:47:13)
    at /home/saas/nodebb/node_modules/nodebb-plugin-smoothshorts/lib/settings.js:33:5
    at handleCallback (/home/saas/nodebb/node_modules/mongodb/lib/utils.js:96:12)
    at /home/saas/nodebb/node_modules/mongodb/lib/collection.js:1357:5
    at handleCallback (/home/saas/nodebb/node_modules/mongodb/lib/utils.js:96:12)
    at /home/saas/nodebb/node_modules/mongodb/lib/cursor.js:657:5
    at handleCallback (/home/saas/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:159:5)
    at setCursorNotified (/home/saas/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:490:3)
    at /home/saas/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:561:16
    at queryCallback (/home/saas/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:220:18)
    at Callbacks.emit (/home/saas/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:119:3)
    at null.messageHandler (/home/saas/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:295:23)
    at Socket.<anonymous> (/home/saas/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:285:22)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
```

**Comment by spicewiesel** [comment]
same for me, v1.1.2
